name: Publish Python Package to PyPI

on:
  release:
    types: [published]
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all history and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch twine

      - name: Build package with Hatch
        run: |
          hatch build
          twine check dist/*

      - name: Publish to PyPI with Hatch
        env:
          # No API token needed with trusted publishing
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ""
        run: hatch publish --user __token__ --auth ""
